#!/bin/sh

set -e

# Alpine deps
apk add --update -t build-deps go git mercurial bzr
apk add -u musl

# GO Magic
goDir="$(go list -e -f '{{.ImportComment}}' 2>/dev/null || true)"

if [ -z "$goDir" -a -s .godir ]; then
    goDir="$(cat .godir)"
fi

dir="$(pwd -P)"
if [ "$goDir" ]; then
    goBin="/bin/$(basename "$goDir")"
else
    goBin="/bin/$(basename "$dir")" # likely "app"
fi

if [ -d "Godeps" ]; then
    go get github.com/tools/godep
    godep restore
fi
go get -v -d
go build -ldflags "-X main.Version $1" -o $goBin

echo $goBin > /tmp/go-bin-name

# Cleanup Alpine deps
apk del --purge build-deps
rm -rf /go /var/cache/apk/*
